/** Compile authoring sources into a native, opt-in Paperclip team. */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  CATALOG_PATH,
  CATALOG_KEY,
  validatePreset,
  allocateBudgets,
  adapterFor,
  runtimeFor,
  permissionsFor,
  topological,
  invariant,
} from "./model.mjs";
export const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const SOURCE = "company/evidence-first";
const GENERATED =
  "Generated by scripts/company/generate.mjs. Edit company/evidence-first, not this file.";
export async function loadSources(root = ROOT) {
  const preset = validatePreset(
    JSON.parse(
      await fs.readFile(path.join(root, SOURCE, "preset.json"), "utf8"),
    ),
  );
  const common = await fs.readFile(
    path.join(root, SOURCE, "COMMON.md"),
    "utf8",
  );
  const roles = {};
  for (const role of preset.roles)
    roles[role.slug] = await fs.readFile(
      path.join(root, SOURCE, "roles", `${role.slug}.md`),
      "utf8",
    );
  return { preset, common, roles };
}
// JSON scalars are valid YAML and supported by the native frontmatter parser.
function yaml(record) {
  return Object.entries(record)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join("\n");
}
function markdown(frontmatter, body) {
  return `---\n${yaml(frontmatter)}\n---\n\n<!-- ${GENERATED} -->\n\n${body.trim()}\n`;
}
export function compileTeam({ preset, common, roles }) {
  validatePreset(preset);
  const files = {},
    agents = {},
    projects = {},
    tasks = {},
    budgets = allocateBudgets(preset);
  for (const role of topological(preset.roles, (r) =>
    r.manager ? [r.manager] : [],
  )) {
    invariant(
      typeof roles[role.slug] === "string" && roles[role.slug].trim(),
      "MISSING_ROLE_INSTRUCTIONS",
    );
    files[`agents/${role.slug}/AGENTS.md`] = markdown(
      {
        name: role.slug,
        slug: role.slug,
        kind: "agent",
        title: role.name,
        role: "general",
        reportsTo: role.manager,
        skills: [],
      },
      `${common.trim()}\n\n---\n\n${roles[role.slug].trim()}`,
    );
    agents[role.slug] = {
      role: "general",
      capabilities: role.name,
      adapter: { type: "codex_local", config: adapterFor(role) },
      runtime: runtimeFor(),
      permissions: permissionsFor(),
      budgetMonthlyCents: budgets[role.slug],
      metadata: {
        evidenceFirst: { role: role.slug, reviewer: role.reviewer, version: 1 },
      },
    };
  }
  for (const project of preset.projects) {
    files[`projects/${project.slug}/PROJECT.md`] = markdown(
      {
        name: project.name,
        slug: project.slug,
        kind: "project",
        description: project.description,
        owner: project.lead,
      },
      project.description,
    );
    projects[project.slug] = {
      leadAgentSlug: project.lead,
      status: "backlog",
    };
  }
  for (const task of topological(preset.tasks, (t) => t.blockedBy)) {
    files[`projects/${task.project}/tasks/${task.slug}/TASK.md`] = markdown(
      {
        name: task.title,
        slug: task.slug,
        kind: "task",
        project: task.project,
        recurring: false,
      },
      `${task.description}\n\n## Aceptación\nEntregable inspeccionable, comandos y resultados reales, limitaciones, siguiente responsable humano. No marcar DONE sin evidencia. Esta tarea queda sin asignar hasta autorizar el trabajo.`,
    );
    tasks[task.slug] = {
      status: "backlog",
      priority: "medium",
      blockedBy: task.blockedBy,
    };
  }
  files[".paperclip.yaml"] =
    `# ${GENERATED}\n${yaml({ schema: "paperclip/v1", agents, projects, tasks })}\n`;
  files["TEAM.md"] = markdown(
    {
      name: preset.name,
      description: preset.description,
      schema: "agentcompanies/v1",
      slug: preset.slug,
      category: "company-defaults",
      key: CATALOG_KEY,
      manager: "agents/director/AGENTS.md",
      includes: [
        ...preset.roles
          .filter((r) => r.manager !== null)
          .map((r) => `agents/${r.slug}/AGENTS.md`),
        ...preset.projects.map((p) => `projects/${p.slug}/PROJECT.md`),
      ],
      defaultInstall: false,
      recommendedForCompanyTypes: ["startup", "product", "research"],
      tags: ["evidence-first", "spanish", "human-approval", "bounded-cost"],
      requiredSkills: [],
    },
    `# ${preset.name}\n\nDoce perfiles disponibles bajo demanda; no doce agentes trabajando permanentemente. Este equipo no autoriza gastos ni envíos externos.\n\nLa instalación del catálogo conserva los bindings declarados y pausa automations por defecto. Mantén la company pausada hasta completar la cualificación descrita en company/README.md. Los workers tienen timer y wake-on-demand desactivados, sin habilidades externas ni credenciales.\n\nLos presupuestos son límites de ejemplo (USD), no financiación autorizada. El límite global exige instalar y verificar company-bwrap; maxConcurrentRuns solo limita cada agente. El aislamiento git_worktree exige comprobar la feature de workspaces de la versión instalada.\n\nNo instales este equipo dos veces usando rename. Revisa preview, contentHash y los agentes existentes. Usa el instalador seguro del fork para exigir una company vacía, pausada y un hash revisado.\n\nLas prohibiciones en los prompts no sustituyen controles de permisos, sandbox, red o revisión humana.`,
  );
  return files;
}
export async function generatedDrift(root = ROOT) {
  const files = compileTeam(await loadSources(root)),
    drift = [];
  for (const [relative, content] of Object.entries(files)) {
    try {
      if (
        (await fs.readFile(path.join(root, CATALOG_PATH, relative), "utf8")) !==
        content
      )
        drift.push(relative);
    } catch {
      drift.push(relative);
    }
  }
  async function visit(dir, prefix = "") {
    for (const entry of await fs
      .readdir(dir, { withFileTypes: true })
      .catch(() => [])) {
      const rel = prefix + entry.name;
      if (entry.isSymbolicLink()) drift.push(rel);
      else if (entry.isDirectory())
        await visit(path.join(dir, entry.name), rel + "/");
      else if (!Object.hasOwn(files, rel)) drift.push(rel);
    }
  }
  await visit(path.join(root, CATALOG_PATH));
  return [...new Set(drift)];
}
export async function generate(root = ROOT) {
  const files = compileTeam(await loadSources(root));
  for (const [relative, content] of Object.entries(files)) {
    const dest = path.join(root, CATALOG_PATH, relative);
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.writeFile(dest, content);
  }
  const drift = await generatedDrift(root);
  invariant(drift.length === 0, "STALE_GENERATED_FILES_REMOVE_AFTER_REVIEW");
  return Object.keys(files).length;
}
if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    if (process.argv.slice(2).length && process.argv[2] !== "--check")
      throw new Error("Usage: node scripts/company/generate.mjs [--check]");
    if (process.argv[2] === "--check") {
      const drift = await generatedDrift();
      console.log(JSON.stringify({ drift }));
      process.exitCode = drift.length ? 1 : 0;
    } else
      console.log(
        JSON.stringify({
          generated: await generate(),
          next: "pnpm --filter @paperclipai/teams-catalog build:manifest",
        }),
      );
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
